### ISSUE TITLE
Hilight not working?

### ISSUE THREAD

**Issue by MikkoMajuri** [falsovsky/FiSH-irssi#23]
Me and my friends have noticed that hilight is not working on any of us that have this FiSH loaded.

**Comment by falsovsky** [comment]
Hi, please post a screenshot or something. I just tried and it works correctly here.
Or tell me how to reproduce it.

**Comment by MikkoMajuri** [comment]
![No hilight 1](http://kinky.fi/mikma/fish/nohilight1.png)
![No hilight 2](http://kinky.fi/mikma/fish/nohilight2.png)

config:
fish = { mark_encrypted = "\0038@\003 "; plain_prefix = "< "; };

**Comment by falsovsky** [comment]
![untitled](https://cloud.githubusercontent.com/assets/142947/7801264/d98fbdb2-0319-11e5-82b2-d89b5935db0c.png)

I just defined the options as you stated, and it still works.

**Comment by falsovsky** [comment]
Ok, it seems to be related to the default irssi theme... going to look further into it

**Comment by falsovsky** [comment]
Well, I have debugged it further.

It seems that the irssi nick hilight implementation doesnt like if something is before the nick. It just works if the nick is the first thing of the message.

I now tried to put the "markencrypted" at the end of the message with "/set mark_position 0" and it started working.

I'll try to see if I can fix this somehow on FiSH, in the meanwhile you can get a ghetto fix by doing "/hilight your_nick".

This is even better IMEO because it also highlights even if your nick isnt the first thing of the message.

**Comment by MikkoMajuri** [comment]
Yes indeedie. Ghetto fix works. Confirmed that too couple of hours ago. But atleast now you know there's something wrong with it in case you do plan on "fixing" this :)
