### ISSUE TITLE
DH1080_INIT not working

### ISSUE THREAD

**Issue by Carmageddon** [falsovsky/FiSH-irssi#37]
Hi, there seems to be a problem in 1on1 fish when the other party is doing the init.
For example:
DH1080_INIT
gi7IeDOV6sAsS/mQZGFu1kgdxd/4VPb+2TEunD8jOZTJ66DDgxb8KYE4P1p2XyCIG0iX9wwBPAVHJ+JOSJL+sqq10adPhLzeNc3ZXp2RCMrALSVODKQIBbYHwdABs0N96wunu/U7TmW5kxwtEW0c551dmU8Ny+u5t+As5KHqKqbN7tzSRlMYA CBC

And when I run a manual check on that nick:
16:25 -!- FiSH: Key for Nick@Network not found or invalid!

However when** I **do the /keyx, it works and we can chat encrypted. Why is that? from what I read, it seems related to Fish-irssi CBC support...

**Comment by falsovsky** [comment]
Hi there!

Yes, CBC isnt supported by FiSH-irssi. But pull requests are accepted :-P

**Comment by Carmageddon** [comment]
Unfortunately my C knowledge is very limited - I wouldn't know where to begin testing this even...

**Comment by falsovsky** [comment]
Then you are as me :-) 

I'm just maintaining this, because I still use it, but the abandoned version was very hard to build.

I just added some few modifications, like cmake building and multiserver support, and some friends removed the dependecy of miracl, and started using OpenSSL instead.

I dont know much about cryptography, if I knew I would gladly implement this, because I know many other FiSH plugins support CBC encryption.
